### ISSUE TITLE
About pose estimation model

### ISSUE THREAD

**Issue by 0x3f3f3f3f3f3f3f3f3f3f3** [xuyankun/STViG-for-READS-V#2]
Among the uploaded files, there is no code that can work out the location of key points in the picture and the extract_patches part needs it(kpts). Could you please upload the pose estimation model fine-tuned by the openpose?

**Comment by xuyankun** [comment]
Thanks for your attention, I have mentioned your concerns in the README.md [pose.pth](https://github.com/xuyankun/VSViG/blob/main/pose.pth)

**Comment by 0x3f3f3f3f3f3f3f3f3f3f3** [comment]
Thanks for your apply, I have noticed the pose.pth file. However, it only include the weight and other parameters.I'm not sure if it is my problem. I have not found the model file.

**Comment by xuyankun** [comment]
@0x3f3f3f3f3f3f3f3f3f3f3 You need follow the the tutorial of [lightweight-openpose](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch), and run the demo. Then you can just replace the model file with pose.pth to run our provided video dataset.

**Comment by 0x3f3f3f3f3f3f3f3f3f3f3** [comment]
I have solved the problem. Thank you very much
